project:
  type: website
  output-dir: _site

website:
  title: "memexponent | Building systems. Learning AI Engineering."
  site-url: https://memexponent.net
  navbar:
    right:
      - charter.qmd
      - about.qmd
      - icon: github
        href: https://github.com/crossjam
      - icon: linkedin
        href: https://linkedin.com/in/crossjam

  draft-mode: visible
  
format:
  html:
    theme:
      - minty
      - cosmo
      - brand
    css: styles.css



