project:
  type: website

website:
  title: "memexponent | bmdphd’s AI engineering explorations"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/crossjam
      - icon: linkedin
        href: https://linkedin.com/in/crossjam

format:
  html:
    theme:
      - minty
      - cosmo
      - brand
    css: styles.css



