---
title: "About"
about:
  template: solana
  links:
    - text: bmdphd
      href: https://bmdphd.info/
    - text: crossjam
      href: https://mpr.crossjam.net/
---


## Why
Memexponent was created to provide a nexus for 
system building explorations independently developed by [Brian M. Dennis,
PHD](https://bmdphd.info/), a.k.a. _bmdphd_. For many decades now, I
have also appeared across The Internets as _crossjam_.

Getting laid off in August 2025 (collateral damage of US federal
research and development funding cuts) left me with a bit of free time
for deep diving into some technical areas that had long been on my
mind. Broadly construed these are in the area of AI Engineering,
building applications using modern generative AI capabilities. 

As well, I wanted to create a public project portfolio that I can
freely share in prospective employment engagements. Something of my
own unlocked from past jobs.

The [charter](charter.qmd) captures the technical goals in a tightly
distilled fashion. Give that a read if you’re in a hurry. Meanwhile,
I’ll take a few liberties and blather on a bit.

## Themes

What even is AI Engineering? Chip Huyen has a pretty good [definition
and book](https://huyenchip.com/books/) (_buy it!_).

> This book discusses AI engineering: the process of building
> applications with readily available foundation models. It introduces
> a practical framework for developing an AI application and
> efficiently deploying it. 

> It also covers how to navigate the AI landscape, including models,
> datasets, evaluation benchmarks, and the seemingly infinite number of
> use cases and application patterns. 


AI Engineering a ridiculously broad space so here a few specific themes I’d
like to emerge as I work on these projects. 

**Agentic Coding**. AI seems promising as a tool for increasing
  developer productivity. There’s not a large body of rigorous work
  pointing pro or con. I’m skeptically optimistic based upon my
  reading of the technology media landscape. The best way to gather
  more evidence is to dive in and build things using tools like,
  [aider][1], [Claude Code][3], [Zed][2], etc. So that’s what I’m
  doing. Man in the AIrena.
  
**Retrieval Augmented Generation (RAG)**. Supplementing LLM based
  systems with information retrieval capabilities was a red hot engine
  of the hype cycle a year or two ago. The hype’s cooled off a bit,
  other than proclamations that "Rag is Dead", but pragmatic industry
  knowledge seems to be maturing. Information retrieval is just the
  fancy academic way to say "search" and that’s long been a latent
  interest of mine, just from a pure systems perspective.
  
 **Systematic AI Evals**. Before getting dismissed, I spent some time
  researching approaches to evaluating Generative AI systems. There’s
  an ever expanding galaxy of academic benchmarks and leaderboards for
  assessment. In addition, there are many different approaches to
  drive these systems, collect inputs and outputs, and calculate
  evaluation metrics. I’m a huge exponent of work from [Eugene
  Yan](https://eugeneyan.com/tag/eval/), [Hamel
  Husain](https://hamel.dev/blog/posts/evals-faq/), and others in this
  area. Always on the lookout for similar creators.
  
**Context Engineering**. This concept has only gained tractions over
the last few months but it definitely resonates. Where I used to be
dismissive of prompt engineering, I have now come around to taking
seriously the technical challenges of getting an LLM good
context. Phil Schmid has [a good
overview](https://www.philschmid.de/context-engineering):

> Context Engineering is the discipline of designing and building
> dynamic systems that provides the right information and tools, in
> the right format, at the right time, to give a LLM everything it
> needs to accomplish a task. 

I have a hunch that some principles and techniques from the compiler
community can provide a lot of leverage in this space.
  
**Improved Software Engineering**. Even though I’ve been at it for a
while, I wouldn’t consider myself a "professional" developer. I’ve
written lots of research code but haven’t set foot near a production
system. This is an opportunity to grow my abilities in a number of
software engineering practices, like testing for example.
  
## Projects

[retrocast](https://github.com/crossjam/retrocast) is AI-assisted retrospective
exploration of podcast episode archives. I have been subscribed to a
decent number of podcasts for a solid decade now. Often times a new
technology emerges as a theme across multiple podcasts. I then have
questions like, "where else in my space of episodes did this concept
appear?", and "how long ago was the first appearance?". I also have
questions about persons, places, and things from a longitudinal
perspective, such as "whatever happened to that company FooScape?".

[feedscope](https://github.com/crossjam/feedscope) could be construed
as the RSS feed version of retrocast. This project is more about
pushing as fast and as far with agentic coding as possible. The basis
is an extremely well documented API for the Feedbin aggregator
service. How

prompthound is a pluralistic approach to examining Cory Doctorow’s
blogging for the discerning craphound. Cory is a renowned author,
activist, and blogger. After leaving BoingBoing and starting
[Pluralistic](https://pluralistic.net) all of his blog content is
readily available in full via RSS feed. A bit of a fanboi expedition,
here I’m creating innovative search toys on top of this text dense,
link rich, longitudinal, violently "of the Web" content.

## Technologies

A smorgasbord of stuff that I either use routinely or have definitie
plans for engaging with soon.

**LLM Developer Toolkitss**. [llm](https://llm.datasette.io),
[PydanticAI](https://ai.pydantic.dev),

**LLM Aggregator APIs**. [OpenRouter](https://openrouter.ai),
[TogetherAI](https://together.ai),
[FireworksAI](https://fireworks.ai), et. al.

**Local Model Platforms**. [LMStudio](https://lmstudio.ai),
[ollama](https://ollama.com),
[llamafile](https://github.com/Mozilla-Ocho/llamafile),
[mlx](https://github.com/ml-explore)

**Model Context Protocol (MCP)**. [modelcontextprotocol.io](https://modelcontextprotocol.io)

**Eval frameworks**. [Pydantic Evals](https://ai.pydantic.dev/evals/),
[promptfoo](https://www.promptfoo.dev),
[Inspect](https://inspect.aisi.org.uk), [MLflow
Evaluation](https://mlflow.org/docs/3.1.0rc0/llms/llm-evaluate/)

**MLOps Observability Frameworks**. [MLFlow](https://mlflow.org), [Pydantic Logfire](https://pydantic.dev/logfire)

**Marimo Notebooks**. [marimo](https://marimo.io) feels like a well
timed branching of Jupyter principles for the modern AI moment. 

**Coiled**. [Coiled](https://coiled.io) is a nice platform for scaling
Python computations on top of public clouds.

**Hugging Face**. [Hugging Face](https://huggingface.co) is arguably
the premier ecosystem for sharing LLM artifacts such as model
checkpoints and datasets. They also provide model aggregation APIs,
serverless inference, and low code ui deployment.

**Terminal CLI AI Repls**. Investigating what’s out there but I have
this odd itch about an extensible REPL, combined with Agentic
frameworks and MCP as a fruitful playground for high velocity
experimentation with LLMs.

## Etymology

[_memex_](https://en.wikipedia.org/wiki/Memex) 

> A memex (a portmanteau of "memory" and "index") is a hypothetical
> electromechanical device for interacting with microform documents
> and described in Vannevar Bush's 1945 article "As We May Think".
> Bush envisioned the memex as a device in which individuals would
> compress and store all of their books, records, and communications,
> "mechanized so that it may be consulted with exceeding speed and
> flexibility". The individual was supposed to use the memex as an
> automatic personal filing system, making the memex "an enlarged
> intimate supplement to his memory".


[_exponent_](https://en.wiktionary.org/wiki/exponent) (plural exponents)

> 1. One who expounds, represents or advocates. 
> 2. (mathematics) The number by which a value (called the base) is
>    said to be raised to a power in exponentiation. Synonym: power


_memexponent_

1. A hypothetical value by which the power of a memex is
   exponentiated.
2. An advocate of [The Memex
   Method](https://pluralistic.net/2021/05/09/the-memex-method/)
3. A [portmanteauing](https://en.wiktionary.org/wiki/portmanteau#Verb)
of a [portmanteau](https://en.wiktionary.org/wiki/portmanteau#Noun_2). 

[1]: https://aider.chat
[2]: https://zed.dev
[3]: https://www.anthropic.com/claude-code
